<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="chatroom.wsrpc" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ChatRoom" targetNamespace="chatroom.wsrpc">
  <wsdl:types>
    <xsd:schema targetNamespace="chatroom.wsrpc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msgns="rest/chatroom/messages">
            <xsd:element name="newTopic">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="topicName" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="newTopicResponse">
        <xsd:complexType>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="getLastMessageNo">
      	<xsd:complexType>
      		<xsd:sequence>
      			<xsd:element name="topicName" type="xsd:string"></xsd:element>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
      <xsd:element name="getLastMessageNoResponse">
      	<xsd:complexType>
      		<xsd:sequence>
      			<xsd:element name="lastMessageNo" type="xsd:int"></xsd:element>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
            <xsd:element name="getChatMessage">
            	<xsd:complexType>
            		<xsd:sequence>
            			<xsd:element name="topicName" type="xsd:string"></xsd:element>
                        <xsd:element name="messageNo" type="xsd:int"></xsd:element>
                    </xsd:sequence>
            	</xsd:complexType>
            </xsd:element>
            <xsd:element name="getChatMessageResponse">
            	<xsd:complexType>
            		<xsd:sequence>
            			<xsd:element name="ChatMessage" type="tns:ChatMessageType"></xsd:element>
            		</xsd:sequence>
            	</xsd:complexType>
            </xsd:element>
            <xsd:element name="sendMessage">
            	<xsd:complexType>
            		<xsd:sequence>
                        <xsd:element name="topicName" type="xsd:string">
            			</xsd:element>
                        <xsd:element name="ChatMessage"
            				type="tns:ChatMessageType">
            			</xsd:element>
                    </xsd:sequence>
            	</xsd:complexType>
            </xsd:element>
            <xsd:element name="sendMessageResponse">
            	<xsd:complexType>
            	</xsd:complexType>
            </xsd:element>
		<xsd:complexType name="ChatMessageType">
			<xsd:all>
				<xsd:element name="sender" type="xsd:string" maxOccurs="1"
					minOccurs="1">
				</xsd:element>
				<xsd:element name="content" type="xsd:string" maxOccurs="1"
					minOccurs="1">
				</xsd:element>
				<xsd:element name="topic" type="xsd:string" maxOccurs="1"
					minOccurs="0">
				</xsd:element>
				<xsd:element name="serialNumber" type="xsd:int" maxOccurs="1"
					minOccurs="0">
				</xsd:element>
				<xsd:element name="replyTo" type="xsd:int" maxOccurs="1" minOccurs="0"></xsd:element>
			</xsd:all>
		</xsd:complexType>

		<xsd:element name="getTopics">
			<xsd:complexType>
			</xsd:complexType>
		</xsd:element>
		<xsd:element name="getTopicsResponse">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element name="topicName" type="xsd:string" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				</xsd:sequence>
			</xsd:complexType>
		</xsd:element>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="newTopicRequest">
    <wsdl:part element="tns:newTopic" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="newTopicResponse">
    <wsdl:part element="tns:newTopicResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="sendMessageRequest">
  	<wsdl:part name="parameters" element="tns:sendMessage"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="sendMessageResponse">
  	<wsdl:part name="parameters" element="tns:sendMessageResponse"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="getLastMessageNoRequest">
  	<wsdl:part name="parameters" element="tns:getLastMessageNo"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="getLastMessageNoResponse">
  	<wsdl:part name="parameters" element="tns:getLastMessageNoResponse"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="getChatMessageRequest">
  	<wsdl:part name="parameters" element="tns:getChatMessage"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="getChatMessageResponse">
  	<wsdl:part name="parameters" element="tns:getChatMessageResponse"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="getTopicsRequest">
  	<wsdl:part name="parameters" element="tns:getTopics"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="getTopicsResponse">
  	<wsdl:part name="parameters" element="tns:getTopicsResponse"></wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ChatRoom">
    <wsdl:operation name="newTopic">
      <wsdl:input message="tns:newTopicRequest"/>
      <wsdl:output message="tns:newTopicResponse"/>
    </wsdl:operation>
    <wsdl:operation name="sendMessage">
    	<wsdl:input message="tns:sendMessageRequest"></wsdl:input>
    	<wsdl:output message="tns:sendMessageResponse"></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getLastMessageNo">
    	<wsdl:input message="tns:getLastMessageNoRequest"></wsdl:input>
    	<wsdl:output message="tns:getLastMessageNoResponse"></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getChatMessage">
    	<wsdl:input message="tns:getChatMessageRequest"></wsdl:input>
    	<wsdl:output message="tns:getChatMessageResponse"></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getTopics">
    	<wsdl:input message="tns:getTopicsRequest"></wsdl:input>
    	<wsdl:output message="tns:getTopicsResponse"></wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ChatRoomSOAP" type="tns:ChatRoom">
  	<soap:binding style="document"
  		transport="http://schemas.xmlsoap.org/soap/http" />
  	<wsdl:operation name="newTopic">
  		<soap:operation
  			soapAction="chatroom.wsrpc/newTopic" />
  		<wsdl:input>
  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body use="literal" />
  		</wsdl:output>
  	</wsdl:operation>
  	<wsdl:operation name="sendMessage">
  		<soap:operation
  			soapAction="chatroom.wsrpc/sendMessage" />
  		<wsdl:input>
  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body use="literal" />
  		</wsdl:output>
  	</wsdl:operation>
  	<wsdl:operation name="getLastMessageNo">
  		<soap:operation
  			soapAction="chatroom.wsrpc/getLastMessageNo" />
  		<wsdl:input>
  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body use="literal" />
  		</wsdl:output>
  	</wsdl:operation>
  	<wsdl:operation name="getChatMessage">
  		<soap:operation
  			soapAction="chatroom.wsrpc/getChatMessage" />
  		<wsdl:input>
  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body use="literal" />
  		</wsdl:output>
  	</wsdl:operation>
  	<wsdl:operation name="getTopics">
  		<soap:operation
  			soapAction="chatroom.wsrpc/getTopics" />
  		<wsdl:input>
  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body use="literal" />
  		</wsdl:output>
  	</wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ChatRoom">
    <wsdl:port binding="tns:ChatRoomSOAP" name="ChatRoomSOAP">
      <soap:address location="http://localhost:8180/05-chatroom-server/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
